[2025-10-12T09:26:50.081+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-12T09:26:50.134+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SSH.group_routes.upload_via_ssh_routes manual__2025-10-12T09:26:32.270673+00:00 [queued]>
[2025-10-12T09:26:50.161+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SSH.group_routes.upload_via_ssh_routes manual__2025-10-12T09:26:32.270673+00:00 [queued]>
[2025-10-12T09:26:50.162+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-12T09:26:50.202+0000] {taskinstance.py:2327} INFO - Executing <Task(SSHOperator): group_routes.upload_via_ssh_routes> on 2025-10-12 09:26:32.270673+00:00
[2025-10-12T09:26:50.219+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=199) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-12T09:26:50.224+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2025-10-12T09:26:50.226+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SSH', 'group_routes.upload_via_ssh_routes', 'manual__2025-10-12T09:26:32.270673+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpwwu6wwqm']
[2025-10-12T09:26:50.235+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask group_routes.upload_via_ssh_routes
[2025-10-12T09:26:50.371+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SSH.group_routes.upload_via_ssh_routes manual__2025-10-12T09:26:32.270673+00:00 [running]> on host 030cfa6c2cac
[2025-10-12T09:26:50.646+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SSH' AIRFLOW_CTX_TASK_ID='group_routes.upload_via_ssh_routes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T09:26:32.270673+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T09:26:32.270673+00:00'
[2025-10-12T09:26:50.652+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-12T09:26:50.653+0000] {ssh.py:151} INFO - Creating ssh_client
[2025-10-12T09:26:50.655+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-10-12T09:26:50.684+0000] {base.py:84} INFO - Using connection ID 'mariadb_ssh_connection' for task execution.
[2025-10-12T09:26:50.688+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-12T09:26:50.713+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    with self.get_ssh_client() as ssh_client:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in get_ssh_client
    return self.hook.get_conn()
           ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 143, in hook
    return self.ssh_hook
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 125, in ssh_hook
    hook = SSHHook(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/hooks/ssh.py", line 253, in __init__
    raise AirflowException("Missing required param: remote_host")
airflow.exceptions.AirflowException: Missing required param: remote_host
[2025-10-12T09:26:50.729+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SSH, task_id=group_routes.upload_via_ssh_routes, execution_date=20251012T092632, start_date=20251012T092650, end_date=20251012T092650
[2025-10-12T09:26:50.783+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task group_routes.upload_via_ssh_routes (Missing required param: remote_host; 209)
[2025-10-12T09:26:50.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-12T09:26:50.985+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-12T09:26:50.994+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
