[2025-10-13T11:46:13.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-13T11:46:13.782+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_routes.sftp_upload_routes manual__2025-10-13T11:45:58.348392+00:00 [queued]>
[2025-10-13T11:46:13.796+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_routes.sftp_upload_routes manual__2025-10-13T11:45:58.348392+00:00 [queued]>
[2025-10-13T11:46:13.797+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-13T11:46:13.816+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_routes.sftp_upload_routes> on 2025-10-13 11:45:58.348392+00:00
[2025-10-13T11:46:13.826+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T11:46:13.829+0000] {standard_task_runner.py:63} INFO - Started process 159 to run task
[2025-10-13T11:46:13.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SFTP', 'group_routes.sftp_upload_routes', 'manual__2025-10-13T11:45:58.348392+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpzrxhs3o0']
[2025-10-13T11:46:13.832+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask group_routes.sftp_upload_routes
[2025-10-13T11:46:13.904+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SFTP.group_routes.sftp_upload_routes manual__2025-10-13T11:45:58.348392+00:00 [running]> on host 165b2a8d6d15
[2025-10-13T11:46:14.035+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SFTP' AIRFLOW_CTX_TASK_ID='group_routes.sftp_upload_routes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-13T11:45:58.348392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-13T11:45:58.348392+00:00'
[2025-10-13T11:46:14.038+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-13T11:46:14.052+0000] {base.py:84} INFO - Using connection ID 'mariadb_ssh_connection' for task execution.
[2025-10-13T11:46:14.075+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2025-10-13T11:46:14.405+0000] {transport.py:1909} INFO - Authentication (password) successful!
[2025-10-13T11:46:14.554+0000] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2025-10-13T11:46:14.568+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-13T11:46:14.570+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 61, in sftp_upload
    sftp.put(local_path, remote_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/sftp_client.py", line 857, in _request
    return self._read_response(num)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/sftp_client.py", line 909, in _read_response
    self._convert_status(msg)
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/sftp_client.py", line 938, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
[2025-10-13T11:46:14.613+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SFTP, task_id=group_routes.sftp_upload_routes, execution_date=20251013T114558, start_date=20251013T114613, end_date=20251013T114614
[2025-10-13T11:46:14.637+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task group_routes.sftp_upload_routes ([Errno 2] No such file; 159)
[2025-10-13T11:46:14.680+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-13T11:46:14.715+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T11:46:14.719+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
