[2025-10-16T18:29:57.683+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T18:29:57.712+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_routes.copy_via_ssh_routes manual__2025-10-16T18:29:37.354327+00:00 [queued]>
[2025-10-16T18:29:57.726+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_routes.copy_via_ssh_routes manual__2025-10-16T18:29:37.354327+00:00 [queued]>
[2025-10-16T18:29:57.726+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-16T18:29:57.744+0000] {taskinstance.py:2327} INFO - Executing <Task(SFTPOperator): group_routes.copy_via_ssh_routes> on 2025-10-16 18:29:37.354327+00:00
[2025-10-16T18:29:57.753+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=275) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-16T18:29:57.756+0000] {standard_task_runner.py:63} INFO - Started process 325 to run task
[2025-10-16T18:29:57.757+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_routes.copy_via_ssh_routes', 'manual__2025-10-16T18:29:37.354327+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmp1swe9kae']
[2025-10-16T18:29:57.767+0000] {standard_task_runner.py:91} INFO - Job 133: Subtask group_routes.copy_via_ssh_routes
[2025-10-16T18:29:57.858+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_routes.copy_via_ssh_routes manual__2025-10-16T18:29:37.354327+00:00 [running]> on host e6b42f39be87
[2025-10-16T18:29:57.982+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_routes.copy_via_ssh_routes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T18:29:37.354327+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T18:29:37.354327+00:00'
[2025-10-16T18:29:57.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T18:29:57.985+0000] {sftp.py:158} INFO - sftp_hook/ssh_hook not provided or invalid. Trying ssh_conn_id to create SFTPHook.
[2025-10-16T18:29:57.999+0000] {base.py:84} INFO - Using connection ID 'mariadb_ssh_connection' for task execution.
[2025-10-16T18:29:58.000+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-10-16T18:29:58.009+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_10.0)
[2025-10-16T18:29:58.028+0000] {ssh.py:343} INFO - Failed to connect. Sleeping before retry attempt 1
[2025-10-16T18:30:02.240+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_10.0)
[2025-10-16T18:30:02.254+0000] {ssh.py:343} INFO - Failed to connect. Sleeping before retry attempt 2
[2025-10-16T18:30:05.620+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_10.0)
[2025-10-16T18:30:05.633+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T18:30:05.644+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sftp/operators/sftp.py", line 185, in execute
    self.sftp_hook.create_directory(remote_folder)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sftp/hooks/sftp.py", line 211, in create_directory
    conn = self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sftp/hooks/sftp.py", line 126, in get_conn
    self.conn = super().get_conn().open_sftp()
                ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/hooks/ssh.py", line 347, in get_conn
    for attempt in Retrying(
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/hooks/ssh.py", line 354, in get_conn
    client.connect(**connect_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/pkey.py", line 421, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/rsakey.py", line 196, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/paramiko/pkey.py", line 494, in _read_private_key_file
    with open(filename, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn\nNhAAAAAwEAAQAAAgEAuDz+QtLBZTda/mkIaBwu59XRuWDmGxkpt8Xyq6mULdknxKuMvbmj\ndYgsHn+P0IuHwz8BBNntc74R890hCi+gkvSKi+0+6XEvmlIdCrddDbl4xnNT4VnjwjYzEI\nV9dG/LfuG/3j8rsOl415AZLEYnCxp/dTPmHCel7J8Fco3NZ/49YbaO0YgnIACDqjV3TVd9\nQ2hNRnrfo+o05ipMC9o6Tp+JzyR6Rcnc2t53Wo4KMQLGFo6/ONKeyqNJRG7Cl7BOlY9tKA\nArtEgOhUYRrNgTbMuoLoIk66TVuKexHC4vpzC1Gx1krph7f0yJfZ/Usp1ejP/+dwnQoWpc\nty4mNvStmEhY4BOBTTA7WVeoUWM9ZR1t8V6PNPMJT+vpNHsx1iRHegpmxewyGsmgHpt1jH\nPhMzvSfGUN8EnXCbCHf+UW9scvhS5oIDknlSsp0gW4VSQxAPkZiw2eqdJPZ1zivIS8xcQ4\n2kzkw4h3VkavKX4ng5ugzw1fP/aC4sShKFSfkHzPss9ebWMUuTilmg2wVLfzm2D2kudsqZ\ne0sDZq47i1Qpx5LVF4QAsfhLqbnqIlF1Phsvdz4OdxVI8L3+4unqMk+EvZXkPea4yaKyqW\nZJ6tscBm4pqqzRhXZ99pwIQ3ziGudxbTDabrC4Ki6C0JgbyuIEmDM6d3tfIauc86WV4LeC\n0AAAdQoyMPraMjD60AAAAHc3NoLXJzYQAAAgEAuDz+QtLBZTda/mkIaBwu59XRuWDmGxkp\nt8Xyq6mULdknxKuMvbmjdYgsHn+P0IuHwz8BBNntc74R890hCi+gkvSKi+0+6XEvmlIdCr\nddDbl4xnNT4VnjwjYzEIV9dG/LfuG/3j8rsOl415AZLEYnCxp/dTPmHCel7J8Fco3NZ/49\nYbaO0YgnIACDqjV3TVd9Q2hNRnrfo+o05ipMC9o6Tp+JzyR6Rcnc2t53Wo4KMQLGFo6/ON\nKeyqNJRG7Cl7BOlY9tKAArtEgOhUYRrNgTbMuoLoIk66TVuKexHC4vpzC1Gx1krph7f0yJ\nfZ/Usp1ejP/+dwnQoWpcty4mNvStmEhY4BOBTTA7WVeoUWM9ZR1t8V6PNPMJT+vpNHsx1i\nRHegpmxewyGsmgHpt1jHPhMzvSfGUN8EnXCbCHf+UW9scvhS5oIDknlSsp0gW4VSQxAPkZ\niw2eqdJPZ1zivIS8xcQ42kzkw4h3VkavKX4ng5ugzw1fP/aC4sShKFSfkHzPss9ebWMUuT\nilmg2wVLfzm2D2kudsqZe0sDZq47i1Qpx5LVF4QAsfhLqbnqIlF1Phsvdz4OdxVI8L3+4u\nnqMk+EvZXkPea4yaKyqWZJ6tscBm4pqqzRhXZ99pwIQ3ziGudxbTDabrC4Ki6C0JgbyuIE\nmDM6d3tfIauc86WV4LeC0AAAADAQABAAACACTFdajwKA3Tz8s9uuIOl/UJGb/yXVLUwZ0O\nesn0wWCqOhP4elFmov+DA2093/4LTzgyk7k8ZrZmXe5qeNzv1xBlkt5tJlSQ1OOr1mSMZt\nvlo/uVyozMdFcPmr8GKZ0q7/Zdx73rpUR8wLPjbIbH5KSEcCJ8DoYZirYQohV0RGYoWedt\n+JDM6CQsvhqja7GJz/Q7dcrmnMq6JL84e2+VKXSGRorLmMTjjns3kiJGfbW8/DzF1lgYv3\n0pvGaWZavBUlnq46oraI2loRJMAxyYjr304tcPfh9zCX3+qCx78mJf6BGmmvD2+ZUVeU6T\nry/MFXI2aLspABUrZaBg61smGBxZBmpmOOR34X//Y3ICXFT6WZHLfD2KTms2KM9xXXNEIN\nQTYVaLvYBlA4U3g1BVPO4nXRi3WfOA48nkrd70Q56x7qmxcEncw1UcsxZjPv1lo4DVhgzv\nLpDo6w0yV3HPeUVk0siCrvu/PQNgX8i+lfKHzKBcGk6pLHSK8q/o0fk+ggE1BoAxBIwziw\nbGR8yAUJatLp93+YGvUcNxeus3QRV8LsanygT/I6SOTKmfRLltdrm05ksUt81r1UVUlIXX\n+zAamZub+CoigrTixCfj2UQJZOIerSoSkbl+xpneg6J6qe3AcsAF9pQGyOv6ZlvUd8rlpu\nBp3jOgkiu8lAfwdwCxAAABACmPJw4WS2RcaDJzqDg9XDuXWfKuMuxjRX2olZwRH3dXdN8V\nLMuwbVzF25H6T2iliLxB9RPc2FiLcjzLdHHkMLSXzaWgfeN+pDT15S3q6Kr/tqTCV/OuqR\nwodd8MmqIPO6nM2C40Vh4bTUzH/Ncp6OCclxwqlXoAbZowykjO1Ofk7w/BPUIPTgGZ1wyR\njZXaaGcq1T55uR4DFcF92UcHYh17vBN+1hZGNaLtfU8IIhXW0AteyrG44M909oEbXaClM1\n9ifVgST2ywFRTZXsoZQnHBfOsbdo9m8+rRrNkJFabcrRnGoLGrp+ljRbhvQg3FnOc9dFGc\n6Zaq163HjA+ddGwAAAEBAOqw+ok/YlBKT3KfBAkVATrFYzqV83S+opPrzPUSv5kOr2Fya+\nnfz9qfckfzhQb12c0eymeGL2TwDGh/bpzrp9cg7xbJZ0cYi8WCljBJFwDcFeUASBqtYCvH\nOgr1pimARuCa3Hxw7YOUmpAYb+PBdlyyAPwjfPdwdnHFl1mIhGJgm07tgXVXaEblkLi7Gb\nzCnKSfmlTh3sVpkrZTw3FFWudSYtb66tF33nhX3kwSO58IA3075MdiJsHlQ3EtZreW6HJ7\n5FksPuZy6TnK5IimWcdWc/56coxqcYLsVD82nbSXVMnK/5kBgeKySaCCBf/AcNf6Y8kd+O\nva4NZyHHVGp50AAAEBAMj3UHiaaoFBW4eQYvfBY3nInYrOdRZ3OzTFQbVW+g5VlQtwn0pl\nvn+BaO+ejDUNYGJkNsEsZYhbkPpvZwHd7uoAnBvHgOgNy95bRSmtcqpWeslbf0YIhav0OV\n5NZUoxXfGNsRC4cfreqP7MrmkobHnTRQc0Zc1c7XVQTaPbdytiBMuxvjbVmGDlpssORsGS\nN3QXMb+maM+S8T6T1PCqe5gpOdHFJlkvzLLJYxHTc9n+eL0H5yn4OoZrq8WLYob2NH22bL\nCY+V0IT+uKBpdOHIu8CN3V/Lxg+xt8ecvMXuhQdKU9edDRXzTL+zLwZE82knvRm1u86YAL\n96AsAhZT1dEAAAAUYWlyZmxvd0A1ZTQwYmJiMzJlMGMBAgMEBQYH\n-----END OPENSSH PRIVATE KEY-----\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sftp/operators/sftp.py", line 191, in execute
    raise AirflowException(f"Error while transferring {file_msg}, error: {e}")
airflow.exceptions.AirflowException: Error while transferring None, error: [Errno 2] No such file or directory: '-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn\nNhAAAAAwEAAQAAAgEAuDz+QtLBZTda/mkIaBwu59XRuWDmGxkpt8Xyq6mULdknxKuMvbmj\ndYgsHn+P0IuHwz8BBNntc74R890hCi+gkvSKi+0+6XEvmlIdCrddDbl4xnNT4VnjwjYzEI\nV9dG/LfuG/3j8rsOl415AZLEYnCxp/dTPmHCel7J8Fco3NZ/49YbaO0YgnIACDqjV3TVd9\nQ2hNRnrfo+o05ipMC9o6Tp+JzyR6Rcnc2t53Wo4KMQLGFo6/ONKeyqNJRG7Cl7BOlY9tKA\nArtEgOhUYRrNgTbMuoLoIk66TVuKexHC4vpzC1Gx1krph7f0yJfZ/Usp1ejP/+dwnQoWpc\nty4mNvStmEhY4BOBTTA7WVeoUWM9ZR1t8V6PNPMJT+vpNHsx1iRHegpmxewyGsmgHpt1jH\nPhMzvSfGUN8EnXCbCHf+UW9scvhS5oIDknlSsp0gW4VSQxAPkZiw2eqdJPZ1zivIS8xcQ4\n2kzkw4h3VkavKX4ng5ugzw1fP/aC4sShKFSfkHzPss9ebWMUuTilmg2wVLfzm2D2kudsqZ\ne0sDZq47i1Qpx5LVF4QAsfhLqbnqIlF1Phsvdz4OdxVI8L3+4unqMk+EvZXkPea4yaKyqW\nZJ6tscBm4pqqzRhXZ99pwIQ3ziGudxbTDabrC4Ki6C0JgbyuIEmDM6d3tfIauc86WV4LeC\n0AAAdQoyMPraMjD60AAAAHc3NoLXJzYQAAAgEAuDz+QtLBZTda/mkIaBwu59XRuWDmGxkp\nt8Xyq6mULdknxKuMvbmjdYgsHn+P0IuHwz8BBNntc74R890hCi+gkvSKi+0+6XEvmlIdCr\nddDbl4xnNT4VnjwjYzEIV9dG/LfuG/3j8rsOl415AZLEYnCxp/dTPmHCel7J8Fco3NZ/49\nYbaO0YgnIACDqjV3TVd9Q2hNRnrfo+o05ipMC9o6Tp+JzyR6Rcnc2t53Wo4KMQLGFo6/ON\nKeyqNJRG7Cl7BOlY9tKAArtEgOhUYRrNgTbMuoLoIk66TVuKexHC4vpzC1Gx1krph7f0yJ\nfZ/Usp1ejP/+dwnQoWpcty4mNvStmEhY4BOBTTA7WVeoUWM9ZR1t8V6PNPMJT+vpNHsx1i\nRHegpmxewyGsmgHpt1jHPhMzvSfGUN8EnXCbCHf+UW9scvhS5oIDknlSsp0gW4VSQxAPkZ\niw2eqdJPZ1zivIS8xcQ42kzkw4h3VkavKX4ng5ugzw1fP/aC4sShKFSfkHzPss9ebWMUuT\nilmg2wVLfzm2D2kudsqZe0sDZq47i1Qpx5LVF4QAsfhLqbnqIlF1Phsvdz4OdxVI8L3+4u\nnqMk+EvZXkPea4yaKyqWZJ6tscBm4pqqzRhXZ99pwIQ3ziGudxbTDabrC4Ki6C0JgbyuIE\nmDM6d3tfIauc86WV4LeC0AAAADAQABAAACACTFdajwKA3Tz8s9uuIOl/UJGb/yXVLUwZ0O\nesn0wWCqOhP4elFmov+DA2093/4LTzgyk7k8ZrZmXe5qeNzv1xBlkt5tJlSQ1OOr1mSMZt\nvlo/uVyozMdFcPmr8GKZ0q7/Zdx73rpUR8wLPjbIbH5KSEcCJ8DoYZirYQohV0RGYoWedt\n+JDM6CQsvhqja7GJz/Q7dcrmnMq6JL84e2+VKXSGRorLmMTjjns3kiJGfbW8/DzF1lgYv3\n0pvGaWZavBUlnq46oraI2loRJMAxyYjr304tcPfh9zCX3+qCx78mJf6BGmmvD2+ZUVeU6T\nry/MFXI2aLspABUrZaBg61smGBxZBmpmOOR34X//Y3ICXFT6WZHLfD2KTms2KM9xXXNEIN\nQTYVaLvYBlA4U3g1BVPO4nXRi3WfOA48nkrd70Q56x7qmxcEncw1UcsxZjPv1lo4DVhgzv\nLpDo6w0yV3HPeUVk0siCrvu/PQNgX8i+lfKHzKBcGk6pLHSK8q/o0fk+ggE1BoAxBIwziw\nbGR8yAUJatLp93+YGvUcNxeus3QRV8LsanygT/I6SOTKmfRLltdrm05ksUt81r1UVUlIXX\n+zAamZub+CoigrTixCfj2UQJZOIerSoSkbl+xpneg6J6qe3AcsAF9pQGyOv6ZlvUd8rlpu\nBp3jOgkiu8lAfwdwCxAAABACmPJw4WS2RcaDJzqDg9XDuXWfKuMuxjRX2olZwRH3dXdN8V\nLMuwbVzF25H6T2iliLxB9RPc2FiLcjzLdHHkMLSXzaWgfeN+pDT15S3q6Kr/tqTCV/OuqR\nwodd8MmqIPO6nM2C40Vh4bTUzH/Ncp6OCclxwqlXoAbZowykjO1Ofk7w/BPUIPTgGZ1wyR\njZXaaGcq1T55uR4DFcF92UcHYh17vBN+1hZGNaLtfU8IIhXW0AteyrG44M909oEbXaClM1\n9ifVgST2ywFRTZXsoZQnHBfOsbdo9m8+rRrNkJFabcrRnGoLGrp+ljRbhvQg3FnOc9dFGc\n6Zaq163HjA+ddGwAAAEBAOqw+ok/YlBKT3KfBAkVATrFYzqV83S+opPrzPUSv5kOr2Fya+\nnfz9qfckfzhQb12c0eymeGL2TwDGh/bpzrp9cg7xbJZ0cYi8WCljBJFwDcFeUASBqtYCvH\nOgr1pimARuCa3Hxw7YOUmpAYb+PBdlyyAPwjfPdwdnHFl1mIhGJgm07tgXVXaEblkLi7Gb\nzCnKSfmlTh3sVpkrZTw3FFWudSYtb66tF33nhX3kwSO58IA3075MdiJsHlQ3EtZreW6HJ7\n5FksPuZy6TnK5IimWcdWc/56coxqcYLsVD82nbSXVMnK/5kBgeKySaCCBf/AcNf6Y8kd+O\nva4NZyHHVGp50AAAEBAMj3UHiaaoFBW4eQYvfBY3nInYrOdRZ3OzTFQbVW+g5VlQtwn0pl\nvn+BaO+ejDUNYGJkNsEsZYhbkPpvZwHd7uoAnBvHgOgNy95bRSmtcqpWeslbf0YIhav0OV\n5NZUoxXfGNsRC4cfreqP7MrmkobHnTRQc0Zc1c7XVQTaPbdytiBMuxvjbVmGDlpssORsGS\nN3QXMb+maM+S8T6T1PCqe5gpOdHFJlkvzLLJYxHTc9n+eL0H5yn4OoZrq8WLYob2NH22bL\nCY+V0IT+uKBpdOHIu8CN3V/Lxg+xt8ecvMXuhQdKU9edDRXzTL+zLwZE82knvRm1u86YAL\n96AsAhZT1dEAAAAUYWlyZmxvd0A1ZTQwYmJiMzJlMGMBAgMEBQYH\n-----END OPENSSH PRIVATE KEY-----\n'
[2025-10-16T18:30:05.655+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_routes.copy_via_ssh_routes, execution_date=20251016T182937, start_date=20251016T182957, end_date=20251016T183005
[2025-10-16T18:30:05.670+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 133 for task group_routes.copy_via_ssh_routes (Error while transferring None, error: [Errno 2] No such file or directory: '-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn\nNhAAAAAwEAAQAAAgEAuDz+QtLBZTda/mkIaBwu59XRuWDmGxkpt8Xyq6mULdknxKuMvbmj\ndYgsHn+P0IuHwz8BBNntc74R890hCi+gkvSKi+0+6XEvmlIdCrddDbl4xnNT4VnjwjYzEI\nV9dG/LfuG/3j8rsOl415AZLEYnCxp/dTPmHCel7J8Fco3NZ/49YbaO0YgnIACDqjV3TVd9\nQ2hNRnrfo+o05ipMC9o6Tp+JzyR6Rcnc2t53Wo4KMQLGFo6/ONKeyqNJRG7Cl7BOlY9tKA\nArtEgOhUYRrNgTbMuoLoIk66TVuKexHC4vpzC1Gx1krph7f0yJfZ/Usp1ejP/+dwnQoWpc\nty4mNvStmEhY4BOBTTA7WVeoUWM9ZR1t8V6PNPMJT+vpNHsx1iRHegpmxewyGsmgHpt1jH\nPhMzvSfGUN8EnXCbCHf+UW9scvhS5oIDknlSsp0gW4VSQxAPkZiw2eqdJPZ1zivIS8xcQ4\n2kzkw4h3VkavKX4ng5ugzw1fP/aC4sShKFSfkHzPss9ebWMUuTilmg2wVLfzm2D2kudsqZ\ne0sDZq47i1Qpx5LVF4QAsfhLqbnqIlF1Phsvdz4OdxVI8L3+4unqMk+EvZXkPea4yaKyqW\nZJ6tscBm4pqqzRhXZ99pwIQ3ziGudxbTDabrC4Ki6C0JgbyuIEmDM6d3tfIauc86WV4LeC\n0AAAdQoyMPraMjD60AAAAHc3NoLXJzYQAAAgEAuDz+QtLBZTda/mkIaBwu59XRuWDmGxkp\nt8Xyq6mULdknxKuMvbmjdYgsHn+P0IuHwz8BBNntc74R890hCi+gkvSKi+0+6XEvmlIdCr\nddDbl4xnNT4VnjwjYzEIV9dG/LfuG/3j8rsOl415AZLEYnCxp/dTPmHCel7J8Fco3NZ/49\nYbaO0YgnIACDqjV3TVd9Q2hNRnrfo+o05ipMC9o6Tp+JzyR6Rcnc2t53Wo4KMQLGFo6/ON\nKeyqNJRG7Cl7BOlY9tKAArtEgOhUYRrNgTbMuoLoIk66TVuKexHC4vpzC1Gx1krph7f0yJ\nfZ/Usp1ejP/+dwnQoWpcty4mNvStmEhY4BOBTTA7WVeoUWM9ZR1t8V6PNPMJT+vpNHsx1i\nRHegpmxewyGsmgHpt1jHPhMzvSfGUN8EnXCbCHf+UW9scvhS5oIDknlSsp0gW4VSQxAPkZ\niw2eqdJPZ1zivIS8xcQ42kzkw4h3VkavKX4ng5ugzw1fP/aC4sShKFSfkHzPss9ebWMUuT\nilmg2wVLfzm2D2kudsqZe0sDZq47i1Qpx5LVF4QAsfhLqbnqIlF1Phsvdz4OdxVI8L3+4u\nnqMk+EvZXkPea4yaKyqWZJ6tscBm4pqqzRhXZ99pwIQ3ziGudxbTDabrC4Ki6C0JgbyuIE\nmDM6d3tfIauc86WV4LeC0AAAADAQABAAACACTFdajwKA3Tz8s9uuIOl/UJGb/yXVLUwZ0O\nesn0wWCqOhP4elFmov+DA2093/4LTzgyk7k8ZrZmXe5qeNzv1xBlkt5tJlSQ1OOr1mSMZt\nvlo/uVyozMdFcPmr8GKZ0q7/Zdx73rpUR8wLPjbIbH5KSEcCJ8DoYZirYQohV0RGYoWedt\n+JDM6CQsvhqja7GJz/Q7dcrmnMq6JL84e2+VKXSGRorLmMTjjns3kiJGfbW8/DzF1lgYv3\n0pvGaWZavBUlnq46oraI2loRJMAxyYjr304tcPfh9zCX3+qCx78mJf6BGmmvD2+ZUVeU6T\nry/MFXI2aLspABUrZaBg61smGBxZBmpmOOR34X//Y3ICXFT6WZHLfD2KTms2KM9xXXNEIN\nQTYVaLvYBlA4U3g1BVPO4nXRi3WfOA48nkrd70Q56x7qmxcEncw1UcsxZjPv1lo4DVhgzv\nLpDo6w0yV3HPeUVk0siCrvu/PQNgX8i+lfKHzKBcGk6pLHSK8q/o0fk+ggE1BoAxBIwziw\nbGR8yAUJatLp93+YGvUcNxeus3QRV8LsanygT/I6SOTKmfRLltdrm05ksUt81r1UVUlIXX\n+zAamZub+CoigrTixCfj2UQJZOIerSoSkbl+xpneg6J6qe3AcsAF9pQGyOv6ZlvUd8rlpu\nBp3jOgkiu8lAfwdwCxAAABACmPJw4WS2RcaDJzqDg9XDuXWfKuMuxjRX2olZwRH3dXdN8V\nLMuwbVzF25H6T2iliLxB9RPc2FiLcjzLdHHkMLSXzaWgfeN+pDT15S3q6Kr/tqTCV/OuqR\nwodd8MmqIPO6nM2C40Vh4bTUzH/Ncp6OCclxwqlXoAbZowykjO1Ofk7w/BPUIPTgGZ1wyR\njZXaaGcq1T55uR4DFcF92UcHYh17vBN+1hZGNaLtfU8IIhXW0AteyrG44M909oEbXaClM1\n9ifVgST2ywFRTZXsoZQnHBfOsbdo9m8+rRrNkJFabcrRnGoLGrp+ljRbhvQg3FnOc9dFGc\n6Zaq163HjA+ddGwAAAEBAOqw+ok/YlBKT3KfBAkVATrFYzqV83S+opPrzPUSv5kOr2Fya+\nnfz9qfckfzhQb12c0eymeGL2TwDGh/bpzrp9cg7xbJZ0cYi8WCljBJFwDcFeUASBqtYCvH\nOgr1pimARuCa3Hxw7YOUmpAYb+PBdlyyAPwjfPdwdnHFl1mIhGJgm07tgXVXaEblkLi7Gb\nzCnKSfmlTh3sVpkrZTw3FFWudSYtb66tF33nhX3kwSO58IA3075MdiJsHlQ3EtZreW6HJ7\n5FksPuZy6TnK5IimWcdWc/56coxqcYLsVD82nbSXVMnK/5kBgeKySaCCBf/AcNf6Y8kd+O\nva4NZyHHVGp50AAAEBAMj3UHiaaoFBW4eQYvfBY3nInYrOdRZ3OzTFQbVW+g5VlQtwn0pl\nvn+BaO+ejDUNYGJkNsEsZYhbkPpvZwHd7uoAnBvHgOgNy95bRSmtcqpWeslbf0YIhav0OV\n5NZUoxXfGNsRC4cfreqP7MrmkobHnTRQc0Zc1c7XVQTaPbdytiBMuxvjbVmGDlpssORsGS\nN3QXMb+maM+S8T6T1PCqe5gpOdHFJlkvzLLJYxHTc9n+eL0H5yn4OoZrq8WLYob2NH22bL\nCY+V0IT+uKBpdOHIu8CN3V/Lxg+xt8ecvMXuhQdKU9edDRXzTL+zLwZE82knvRm1u86YAL\n96AsAhZT1dEAAAAUYWlyZmxvd0A1ZTQwYmJiMzJlMGMBAgMEBQYH\n-----END OPENSSH PRIVATE KEY-----\n'; 325)
[2025-10-16T18:30:05.702+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T18:30:05.734+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T18:30:05.739+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
