[2025-10-11T19:17:50.485+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T19:17:50.543+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_planes.truncate_table_planes manual__2025-10-11T19:17:42.055999+00:00 [queued]>
[2025-10-11T19:17:50.568+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_planes.truncate_table_planes manual__2025-10-11T19:17:42.055999+00:00 [queued]>
[2025-10-11T19:17:50.570+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T19:17:50.606+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_planes.truncate_table_planes> on 2025-10-11 19:17:42.055999+00:00
[2025-10-11T19:17:50.657+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T19:17:50.662+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_planes.truncate_table_planes', 'manual__2025-10-11T19:17:42.055999+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmplvvuzhxm']
[2025-10-11T19:17:50.679+0000] {standard_task_runner.py:63} INFO - Started process 118 to run task
[2025-10-11T19:17:50.682+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask group_planes.truncate_table_planes
[2025-10-11T19:17:50.787+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_planes.truncate_table_planes manual__2025-10-11T19:17:42.055999+00:00 [running]> on host 187d1545c280
[2025-10-11T19:17:50.987+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_planes.truncate_table_planes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T19:17:42.055999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T19:17:42.055999+00:00'
[2025-10-11T19:17:50.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T19:17:51.011+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-11T19:17:51.013+0000] {mariadb_hook.py:37} INFO - Connecting to MariaDB database: 
[2025-10-11T19:17:51.018+0000] {mariadb_hook.py:41} ERROR - Error connecting to MariaDB: Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
[2025-10-11T19:17:51.019+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T19:17:51.020+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 33, in truncate_if_exists
    result = hook.get_first(sql_check)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 276, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 42, in get_conn
    raise e
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 39, in get_conn
    return mariadb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/__init__.py", line 147, in connect
    connection = connectionclass(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/connections.py", line 85, in __init__
    super().__init__(*args, **kwargs)
mariadb.OperationalError: Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
[2025-10-11T19:17:51.042+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_planes.truncate_table_planes, execution_date=20251011T191742, start_date=20251011T191750, end_date=20251011T191751
[2025-10-11T19:17:51.064+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task group_planes.truncate_table_planes (Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2); 118)
[2025-10-11T19:17:51.081+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T19:17:51.125+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T19:17:51.130+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
