[2025-10-12T09:24:08.955+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-12T09:24:08.983+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SSH.group_airport_extended.download_airport_extended manual__2025-10-12T09:24:04.689338+00:00 [queued]>
[2025-10-12T09:24:08.995+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SSH.group_airport_extended.download_airport_extended manual__2025-10-12T09:24:04.689338+00:00 [queued]>
[2025-10-12T09:24:08.996+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-12T09:24:09.025+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_airport_extended.download_airport_extended> on 2025-10-12 09:24:04.689338+00:00
[2025-10-12T09:24:09.036+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-12T09:24:09.040+0000] {standard_task_runner.py:63} INFO - Started process 134 to run task
[2025-10-12T09:24:09.042+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SSH', 'group_airport_extended.download_airport_extended', 'manual__2025-10-12T09:24:04.689338+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpg8_ys0y6']
[2025-10-12T09:24:09.047+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask group_airport_extended.download_airport_extended
[2025-10-12T09:24:09.140+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SSH.group_airport_extended.download_airport_extended manual__2025-10-12T09:24:04.689338+00:00 [running]> on host 030cfa6c2cac
[2025-10-12T09:24:09.285+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SSH' AIRFLOW_CTX_TASK_ID='group_airport_extended.download_airport_extended' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T09:24:04.689338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T09:24:04.689338+00:00'
[2025-10-12T09:24:09.288+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-12T09:24:09.685+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-12T09:24:09.686+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 29, in download_file
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/jpatokal/openflights/master/data/airport_extended.dat
[2025-10-12T09:24:09.701+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SSH, task_id=group_airport_extended.download_airport_extended, execution_date=20251012T092404, start_date=20251012T092408, end_date=20251012T092409
[2025-10-12T09:24:09.717+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task group_airport_extended.download_airport_extended (404 Client Error: Not Found for url: https://raw.githubusercontent.com/jpatokal/openflights/master/data/airport_extended.dat; 134)
[2025-10-12T09:24:09.754+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-12T09:24:09.787+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-12T09:24:09.792+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
