[2025-10-16T19:35:45.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T19:35:45.149+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.create_database manual__2025-10-16T19:35:39.724485+00:00 [queued]>
[2025-10-16T19:35:45.164+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.create_database manual__2025-10-16T19:35:39.724485+00:00 [queued]>
[2025-10-16T19:35:45.165+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-16T19:35:45.186+0000] {taskinstance.py:2327} INFO - Executing <Task(MariaDBOperator): create_database> on 2025-10-16 19:35:39.724485+00:00
[2025-10-16T19:35:45.198+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=372) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-16T19:35:45.202+0000] {standard_task_runner.py:63} INFO - Started process 385 to run task
[2025-10-16T19:35:45.203+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'create_database', 'manual__2025-10-16T19:35:39.724485+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpayx1p8vt']
[2025-10-16T19:35:45.208+0000] {standard_task_runner.py:91} INFO - Job 180: Subtask create_database
[2025-10-16T19:35:45.293+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.create_database manual__2025-10-16T19:35:39.724485+00:00 [running]> on host e6b42f39be87
[2025-10-16T19:35:45.465+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='create_database' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T19:35:39.724485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T19:35:39.724485+00:00'
[2025-10-16T19:35:45.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T19:35:45.470+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS open_flights_data;
        
[2025-10-16T19:35:45.486+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-16T19:35:45.499+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-16T19:35:45.500+0000] {mariadb_hook.py:38} INFO - Connecting to MariaDB database: open_flights_data
[2025-10-16T19:35:45.508+0000] {mariadb_hook.py:42} ERROR - Error connecting to MariaDB: Access denied for user 'root'@'***-docker-***-worker-1.***_net' (using password: YES)
[2025-10-16T19:35:45.509+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T19:35:45.509+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 43, in get_conn
    raise e
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 40, in get_conn
    return mariadb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/__init__.py", line 94, in connect
    connection = connectionclass(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/connections.py", line 85, in __init__
    super().__init__(*args, **kwargs)
mariadb.OperationalError: Access denied for user 'root'@'***-docker-***-worker-1.***_net' (using password: YES)
[2025-10-16T19:35:45.532+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=create_database, execution_date=20251016T193539, start_date=20251016T193545, end_date=20251016T193545
[2025-10-16T19:35:45.554+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 180 for task create_database (Access denied for user 'root'@'***-docker-***-worker-1.***_net' (using password: YES); 385)
[2025-10-16T19:35:45.589+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T19:35:45.611+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MariaDBOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-10-16T19:35:45.644+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T19:35:45.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
