[2025-10-11T18:53:22.442+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T18:53:22.481+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airports.copy_to_docker_airports manual__2025-10-11T18:53:11.103954+00:00 [queued]>
[2025-10-11T18:53:22.498+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airports.copy_to_docker_airports manual__2025-10-11T18:53:11.103954+00:00 [queued]>
[2025-10-11T18:53:22.498+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T18:53:22.521+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): group_airports.copy_to_docker_airports> on 2025-10-11 18:53:11.103954+00:00
[2025-10-11T18:53:22.530+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=456) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T18:53:22.533+0000] {standard_task_runner.py:63} INFO - Started process 468 to run task
[2025-10-11T18:53:22.534+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_airports.copy_to_docker_airports', 'manual__2025-10-11T18:53:11.103954+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpi6hb56ds']
[2025-10-11T18:53:22.538+0000] {standard_task_runner.py:91} INFO - Job 167: Subtask group_airports.copy_to_docker_airports
[2025-10-11T18:53:22.618+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_airports.copy_to_docker_airports manual__2025-10-11T18:53:11.103954+00:00 [running]> on host dc3f0ff817bf
[2025-10-11T18:53:22.760+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_airports.copy_to_docker_airports' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T18:53:11.103954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T18:53:11.103954+00:00'
[2025-10-11T18:53:22.764+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T18:53:22.766+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-11T18:53:22.767+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker cp /tmp/airports.dat my-***:/var/openflights_data/airports.dat']
[2025-10-11T18:53:22.784+0000] {subprocess.py:86} INFO - Output:
[2025-10-11T18:53:22.814+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-10-11T18:53:22.815+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-11T18:53:22.817+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T18:53:22.834+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-11T18:53:22.841+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_airports.copy_to_docker_airports, execution_date=20251011T185311, start_date=20251011T185322, end_date=20251011T185322
[2025-10-11T18:53:22.870+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 167 for task group_airports.copy_to_docker_airports (Bash command failed. The command returned a non-zero exit code 1.; 468)
[2025-10-11T18:53:22.920+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T18:53:23.024+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T18:53:23.029+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
