[2025-10-11T18:51:13.283+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T18:51:13.331+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airport_extended.copy_to_docker_airport_extended manual__2025-10-11T18:51:01.424250+00:00 [queued]>
[2025-10-11T18:51:13.351+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airport_extended.copy_to_docker_airport_extended manual__2025-10-11T18:51:01.424250+00:00 [queued]>
[2025-10-11T18:51:13.353+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T18:51:13.409+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): group_airport_extended.copy_to_docker_airport_extended> on 2025-10-11 18:51:01.424250+00:00
[2025-10-11T18:51:13.421+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=360) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T18:51:13.424+0000] {standard_task_runner.py:63} INFO - Started process 374 to run task
[2025-10-11T18:51:13.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_airport_extended.copy_to_docker_airport_extended', 'manual__2025-10-11T18:51:01.424250+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpwkh5utyh']
[2025-10-11T18:51:13.431+0000] {standard_task_runner.py:91} INFO - Job 151: Subtask group_airport_extended.copy_to_docker_airport_extended
[2025-10-11T18:51:13.523+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_airport_extended.copy_to_docker_airport_extended manual__2025-10-11T18:51:01.424250+00:00 [running]> on host dc3f0ff817bf
[2025-10-11T18:51:13.715+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_airport_extended.copy_to_docker_airport_extended' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T18:51:01.424250+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T18:51:01.424250+00:00'
[2025-10-11T18:51:13.719+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T18:51:13.721+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-11T18:51:13.723+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker cp /tmp/airport_extended.dat ***-docker:/var/openflights_data/airport_extended.dat']
[2025-10-11T18:51:13.748+0000] {subprocess.py:86} INFO - Output:
[2025-10-11T18:51:13.785+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-10-11T18:51:13.788+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-11T18:51:13.789+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T18:51:13.811+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-11T18:51:13.821+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_airport_extended.copy_to_docker_airport_extended, execution_date=20251011T185101, start_date=20251011T185113, end_date=20251011T185113
[2025-10-11T18:51:13.847+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 151 for task group_airport_extended.copy_to_docker_airport_extended (Bash command failed. The command returned a non-zero exit code 1.; 374)
[2025-10-11T18:51:13.898+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T18:51:14.082+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T18:51:14.090+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
