[2025-10-16T17:07:30.169+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T17:07:30.195+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.create_database manual__2025-10-16T17:07:20.087853+00:00 [queued]>
[2025-10-16T17:07:30.205+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.create_database manual__2025-10-16T17:07:20.087853+00:00 [queued]>
[2025-10-16T17:07:30.206+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-16T17:07:30.224+0000] {taskinstance.py:2327} INFO - Executing <Task(MariaDBOperator): create_database> on 2025-10-16 17:07:20.087853+00:00
[2025-10-16T17:07:30.245+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-16T17:07:30.286+0000] {standard_task_runner.py:63} INFO - Started process 90 to run task
[2025-10-16T17:07:30.256+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'create_database', 'manual__2025-10-16T17:07:20.087853+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmp05v610ko']
[2025-10-16T17:07:30.292+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask create_database
[2025-10-16T17:07:30.445+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.create_database manual__2025-10-16T17:07:20.087853+00:00 [running]> on host 6c399496d1bd
[2025-10-16T17:07:30.711+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='create_database' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T17:07:20.087853+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T17:07:20.087853+00:00'
[2025-10-16T17:07:30.728+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T17:07:30.731+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS open_flights_data;
        
[2025-10-16T17:07:30.788+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-16T17:07:30.811+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-16T17:07:30.812+0000] {mariadb_hook.py:38} INFO - Connecting to MariaDB database: open_flights_data
[2025-10-16T17:07:30.822+0000] {mariadb_hook.py:42} ERROR - Error connecting to MariaDB: Unknown database 'open_flights_data'
[2025-10-16T17:07:30.823+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T17:07:30.824+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 43, in get_conn
    raise e
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 40, in get_conn
    return mariadb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/__init__.py", line 94, in connect
    connection = connectionclass(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/connections.py", line 85, in __init__
    super().__init__(*args, **kwargs)
mariadb.ProgrammingError: Unknown database 'open_flights_data'
[2025-10-16T17:07:30.840+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=create_database, execution_date=20251016T170720, start_date=20251016T170730, end_date=20251016T170730
[2025-10-16T17:07:30.859+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task create_database (Unknown database 'open_flights_data'; 90)
[2025-10-16T17:07:30.893+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T17:07:30.910+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MariaDBOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-10-16T17:07:30.943+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T17:07:30.949+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
