[2025-10-13T11:55:51.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-13T11:55:51.113+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_planes.cpimport_planes manual__2025-10-13T11:50:29.073841+00:00 [queued]>
[2025-10-13T11:55:51.127+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_planes.cpimport_planes manual__2025-10-13T11:50:29.073841+00:00 [queued]>
[2025-10-13T11:55:51.128+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-10-13T11:55:51.150+0000] {taskinstance.py:2327} INFO - Executing <Task(MariaDBCpImportOperator): group_planes.cpimport_planes> on 2025-10-13 11:50:29.073841+00:00
[2025-10-13T11:55:51.159+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T11:55:51.161+0000] {standard_task_runner.py:63} INFO - Started process 272 to run task
[2025-10-13T11:55:51.163+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SFTP', 'group_planes.cpimport_planes', 'manual__2025-10-13T11:50:29.073841+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpqrvb44my']
[2025-10-13T11:55:51.167+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask group_planes.cpimport_planes
[2025-10-13T11:55:51.238+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SFTP.group_planes.cpimport_planes manual__2025-10-13T11:50:29.073841+00:00 [running]> on host 165b2a8d6d15
[2025-10-13T11:55:51.354+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SFTP' AIRFLOW_CTX_TASK_ID='group_planes.cpimport_planes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-13T11:50:29.073841+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-13T11:50:29.073841+00:00'
[2025-10-13T11:55:51.357+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-13T11:55:51.358+0000] {mariadb_cpimport_operator.py:83} INFO - Starting cpimport operation for table: planes
[2025-10-13T11:55:51.359+0000] {mariadb_cpimport_operator.py:84} INFO - Source file: /var/openflights_data/planes.dat
[2025-10-13T11:55:51.359+0000] {mariadb_cpimport_operator.py:92} INFO - Validating ColumnStore engine...
[2025-10-13T11:55:51.371+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-13T11:55:51.372+0000] {mariadb_hook.py:37} INFO - Connecting to MariaDB database: 
[2025-10-13T11:55:51.378+0000] {mariadb_hook.py:78} INFO - Table open_flights_data.planes uses engine: InnoDB
[2025-10-13T11:55:51.379+0000] {mariadb_hook.py:82} ERROR - Table open_flights_data.planes uses InnoDB engine, but ColumnStore is required for cpimport
[2025-10-13T11:55:51.380+0000] {mariadb_cpimport_operator.py:114} ERROR - ‚ùå cpimport operation failed: Table open_flights_data.planes uses InnoDB engine, but ColumnStore is required for cpimport
[2025-10-13T11:55:51.380+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-13T11:55:51.392+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/operators/mariadb_cpimport_operator.py", line 93, in execute
    hook.validate_columnstore_engine(self.table_name, self.schema)
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 83, in validate_columnstore_engine
    raise AirflowException(error_msg)
airflow.exceptions.AirflowException: Table open_flights_data.planes uses InnoDB engine, but ColumnStore is required for cpimport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/operators/mariadb_cpimport_operator.py", line 115, in execute
    raise AirflowException(f"cpimport operation failed: {e}")
airflow.exceptions.AirflowException: cpimport operation failed: Table open_flights_data.planes uses InnoDB engine, but ColumnStore is required for cpimport
[2025-10-13T11:55:51.401+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SFTP, task_id=group_planes.cpimport_planes, execution_date=20251013T115029, start_date=20251013T115551, end_date=20251013T115551
[2025-10-13T11:55:51.420+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task group_planes.cpimport_planes (cpimport operation failed: Table open_flights_data.planes uses InnoDB engine, but ColumnStore is required for cpimport; 272)
[2025-10-13T11:55:51.468+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-13T11:55:51.524+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T11:55:51.527+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
