[2025-10-13T12:18:56.267+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-13T12:18:56.310+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_routes.create_table_routes manual__2025-10-13T12:13:40.789273+00:00 [queued]>
[2025-10-13T12:18:56.326+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_routes.create_table_routes manual__2025-10-13T12:13:40.789273+00:00 [queued]>
[2025-10-13T12:18:56.326+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-10-13T12:18:56.352+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_routes.create_table_routes> on 2025-10-13 12:13:40.789273+00:00
[2025-10-13T12:18:56.362+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T12:18:56.364+0000] {standard_task_runner.py:63} INFO - Started process 328 to run task
[2025-10-13T12:18:56.365+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SFTP', 'group_routes.create_table_routes', 'manual__2025-10-13T12:13:40.789273+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpusl5rjdb']
[2025-10-13T12:18:56.369+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask group_routes.create_table_routes
[2025-10-13T12:18:56.447+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SFTP.group_routes.create_table_routes manual__2025-10-13T12:13:40.789273+00:00 [running]> on host 165b2a8d6d15
[2025-10-13T12:18:56.591+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SFTP' AIRFLOW_CTX_TASK_ID='group_routes.create_table_routes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-13T12:13:40.789273+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-13T12:13:40.789273+00:00'
[2025-10-13T12:18:56.597+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-13T12:18:56.613+0000] {base.py:84} INFO - Using connection ID 'maria_db_default' for task execution.
[2025-10-13T12:18:56.614+0000] {mariadb_hook.py:37} INFO - Connecting to MariaDB database: 
[2025-10-13T12:18:56.624+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-13T12:18:56.628+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 45, in create_table
    cursor.execute(ddl_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/mariadb/cursors.py", line 351, in execute
    self._readresponse()
mariadb.OperationalError: Internal error: Cannot execute the statement. DBRM is read only!
[2025-10-13T12:18:56.648+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SFTP, task_id=group_routes.create_table_routes, execution_date=20251013T121340, start_date=20251013T121856, end_date=20251013T121856
[2025-10-13T12:18:56.668+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task group_routes.create_table_routes (Internal error: Cannot execute the statement. DBRM is read only!; 328)
[2025-10-13T12:18:56.713+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-13T12:18:56.775+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T12:18:56.781+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
