[2025-10-11T18:33:57.407+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T18:33:57.458+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airports.copy_to_docker_airports manual__2025-10-11T18:33:45.880086+00:00 [queued]>
[2025-10-11T18:33:57.477+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airports.copy_to_docker_airports manual__2025-10-11T18:33:45.880086+00:00 [queued]>
[2025-10-11T18:33:57.481+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T18:33:57.513+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): group_airports.copy_to_docker_airports> on 2025-10-11 18:33:45.880086+00:00
[2025-10-11T18:33:57.525+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T18:33:57.528+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2025-10-11T18:33:57.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_airports.copy_to_docker_airports', 'manual__2025-10-11T18:33:45.880086+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpmfp1aesx']
[2025-10-11T18:33:57.544+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask group_airports.copy_to_docker_airports
[2025-10-11T18:33:57.642+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_airports.copy_to_docker_airports manual__2025-10-11T18:33:45.880086+00:00 [running]> on host dc3f0ff817bf
[2025-10-11T18:33:57.808+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_airports.copy_to_docker_airports' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T18:33:45.880086+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T18:33:45.880086+00:00'
[2025-10-11T18:33:57.811+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T18:33:57.812+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-11T18:33:57.814+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker cp /tmp/airports.dat mcs1:/var/openflights_data/airports.dat']
[2025-10-11T18:33:57.829+0000] {subprocess.py:86} INFO - Output:
[2025-10-11T18:33:57.929+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-10-11T18:33:57.929+0000] {subprocess.py:93} INFO - time="2025-10-11T18:33:57Z" level=error msg="Can't add file /tmp/airports.dat to tar: io: read/write on closed pipe"
[2025-10-11T18:33:57.930+0000] {subprocess.py:93} INFO - time="2025-10-11T18:33:57Z" level=error msg="Can't close tar writer: io: read/write on closed pipe"
[2025-10-11T18:33:57.931+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-11T18:33:57.932+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T18:33:57.946+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-11T18:33:57.954+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_airports.copy_to_docker_airports, execution_date=20251011T183345, start_date=20251011T183357, end_date=20251011T183357
[2025-10-11T18:33:57.999+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 113 for task group_airports.copy_to_docker_airports (Bash command failed. The command returned a non-zero exit code 1.; 176)
[2025-10-11T18:33:58.043+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T18:33:58.152+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T18:33:58.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
